### ISSUE TITLE
Downloading prebuilt cryptopp is broken

### ISSUE THREAD

**Issue by tex0l** [JiriHoffmann/react-native-cryptopp#14]
I think this is related to https://github.com/JiriHoffmann/react-native-cryptopp/blob/b047f4aba0f402f59bcb719663c87a02046ac952/package.json#L4

If changed back to 8.6.0, it works.

**Comment by JiriHoffmann** [comment]
Related to #15, fixed in [#5f6e4](https://github.com/JiriHoffmann/react-native-cryptopp/commit/5f6e4ec36fddbadbe442b1cc5a59c2628e8d8a66)
