### ISSUE TITLE
Support RSA-PSS without recovery

### ISSUE THREAD

**Issue by tex0l** [JiriHoffmann/react-native-cryptopp#16]
Currently, it is not possible to sign / verify something that uses the `RSA-PSS` scheme, it is necessary to use the `RSA-PSSR` scheme which is very similar but includes the data signed.

Would it be possible to support PSS_SHA1, PSSR_SHA256 and PSS_Whirlpool? Implementation seems trivial as it is provided by cryptopp.

**Comment by tex0l** [comment]
EDIT: actually, by mistake, you implemented a RSA-PSS without the recovery because you don't set the `putMessage` in the `SignerFilter` which is `false` by default. This in turn makes the `PSSR-*` schemes incompatible with both the `verify` because the scheme is not supported, and the `recover` because the message is not included in the payload.

Therefore, I would suggest doing a few things:
1. modify `exec_sign` to take a `putMessage` argument that would be passed to `SignerFilter` ([see cryptopp wiki ](https://cryptopp.com/wiki/RSA_Signature_Schemes#Probabilistic_Signature_Scheme_with_Recovery_.28Filter.29));
2. if the scheme is `PSSR-*` set `putMessage` to `true`, if the scheme is `PSS-*` set it to `false`;
3. modify the `verify` to accept the `PSS-*` schemes.

**Comment by JiriHoffmann** [comment]
Check out this PR: https://github.com/JiriHoffmann/react-native-cryptopp/pull/25

**Comment by tex0l** [comment]
The PR seems good to me!

**Comment by JiriHoffmann** [comment]
Closed with #25
