### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by tex0l** [JiriHoffmann/react-native-cryptopp#27]
Hi @JiriHoffmann,

I have tested on iOS and android the latest main version, and it works out of the box for my use case (except for the RSA-PSS, but I need to have a non-standard salt length anyway)! Thank you for the amazing work :).

Would it be possible to make a release on npm please? 🙏

**Comment by JiriHoffmann** [comment]
Yes, totally. I just wanted to update the documentation first and then get a new release out the door

**Comment by JiriHoffmann** [comment]
![image](https://user-images.githubusercontent.com/37304278/188572823-530f54e8-57d8-4454-8336-b058e9a84a54.png)

New release is out!
