### ISSUE TITLE
Expose an async version of the functions

### ISSUE THREAD

**Issue by tex0l** [JiriHoffmann/react-native-cryptopp#28]
Hi @JiriHoffmann,

Currently, any function call to rn-cryptopp is synchronous, it'd be great to have asynchronous equivalents as:
- currently, it blocks the react-native main thread, even if `react-native-cryptopp` is very fast, when generating a 4096bits RSA key, it takes a few seconds during which is app is frozen;
- when using the debugger, synchronous methods don't work, but asynchronous methods do (at least with JNI modules, I'm not sure with JSI modules).

**Comment by JiriHoffmann** [comment]
Only needed to rewrite half of the C++ code once again, but all functions have both synchronous and asynchronous (multi-threaded) variants now

**Comment by mfbx9da4** [comment]
Well done @JiriHoffmann code is looking really clean. I like how you've made a single entry point to allow for any method to be async or not 👏 .
