### ISSUE TITLE
Progressive hashing does not work with arraybuffer anymore

### ISSUE THREAD

**Issue by tex0l** [JiriHoffmann/react-native-cryptopp#30]
In the previous implementation without the async and stuff, it was allowed to do progressive hashing with an arraybuffer, but it appears it is no longer possible as the type `STRING` is checked, and when I try to update my hash, it fails with `[Error: RNCryptopp: update() expects 1 argument: data].`

See here:

https://github.com/JiriHoffmann/react-native-cryptopp/blob/3224db5aa839d4e4900dd767dbd9eab79baa95a1/cpp/hash-functions-ho.cpp#L32

Here is a test case:
```js
import Cryptopp from 'react-native-cryptopp'

const hash = Cryptopp.hash.createHash('SHA256')
const buffer = new ArrayBuffer(8)
const vue = new Int32Array(buffer)
vue[0] = 100
vue[1] = 200
// buffer contains : 64 00 00 00 c8 00 00 00 — but really it doesn't matter
hash.update(buffer)
// fails with [Error: RNCryptopp: update() expects 1 argument: data]
```

**Comment by tex0l** [comment]
It works, thanks a lot!

**Comment by JiriHoffmann** [comment]
Perfect, glad to hear that!
