### ISSUE TITLE
'string' file not found on iOS

### ISSUE THREAD

**Issue by efstathiosntonas** [JiriHoffmann/react-native-cryptopp#4]
While building on Xcode 13.3 (Intel) Monterey 12.3 it throws this error on `config_cxx`

![Screenshot 2022-03-25 at 09 41 51](https://user-images.githubusercontent.com/717975/160076445-be2ad40c-782d-411b-8797-bf5dece4fd1b.png)

let me know if you need any additional info

edit: gcc info:
```
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

~it seems the header is missing, will check if my Mac has c++ 20 support, maybe use `gcc` from Homebrew~

edit 2:

it seems that the `string.h` exists on my `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include` folder, weird stuff.

edit 3:

I'm using this `compile_cryptopp_ios.sh` witch uses `GNUmakefile-cross` as it should.

```bash
#!/bin/bash

TEMP_IOS="TEMP_IOS"
CWD=$(pwd -P)

function build_cryptopp_ios
{
    IOS_SDK="$1" IOS_CPU="$2" source setenv-ios.sh
    make -f GNUmakefile-cross static
    make install -f GNUmakefile-cross PREFIX="$TEMP_IOS"
    mv "$TEMP_IOS/lib/libcryptopp.a" "../cpp/ios/libcryptopp_$2.a"
    mv "$TEMP_IOS/include/cryptopp" "../cpp"
}

# #########################################
# #####           Prepare             #####
# #########################################
pushd "$CWD"
mkdir -p "cpp/cryptopp" "cpp/ios"
sh scripts/copy_pem_pack.sh

# #########################################
# #####              iOS              #####
# #########################################

pushd "cryptopp"
make clean

# Bug fix => https://github.com/weidai11/cryptopp/issues/1074
cp -f "TestScripts/setenv-ios.sh" "setenv-ios.sh"
search="-DNDEBUG"
replace="-DNDEBUG -DCRYPTOPP_DISABLE_ARM_CRC32"
sed -i  -e "s/$search/$replace/g" "setenv-ios.sh"

# Build for physical devices
build_cryptopp_ios iPhoneOS arm64
make clean

# Build for simulator
build_cryptopp_ios iPhoneSimulator i386
make clean

# Build for simulator
build_cryptopp_ios iPhoneSimulator x86_64
make clean

rm -rf "$TEMP_IOS"
popd

# Create fat lib
lipo -create cpp/ios/libcryptopp_arm64.a \
             cpp/ios/libcryptopp_i386.a \
             cpp/ios/libcryptopp_x86_64.a \
     -output cpp/ios/libcryptopp.a
popd

```

**Comment by JiriHoffmann** [comment]
I will try to replicate your setup, but what you are saying is that crypto++ compiles, but then it fails to build the app in Xcode?

**Comment by efstathiosntonas** [comment]
@JiriHoffmann yes, on `pod install` it compiles with no issues, when building on Xcode it shows the error above.

**Comment by JiriHoffmann** [comment]
Not sure if I can get my hands on a Monterey device with Xcode 13 at the moment. You can try using the compiled version that just got released. I have also created another branch [test-macos12-action](https://github.com/JiriHoffmann/react-native-cryptopp/tree/test-macos12-action) and set up an Action to compile the code using XCode 13 but MacOS 12 devices are currently in closed beta so it might be a bit before they make them available

**Comment by JiriHoffmann** [comment]
Just got access to MacOS 12 for GH actions, you can check the run [here](https://github.com/JiriHoffmann/react-native-cryptopp/runs/5978833250?check_suite_focus=true). I was able to build and run the example app without any issues using the newly compiled code so I am guessing it might be a local issue
