### ISSUE TITLE
Expose HMAC (and other message authentication functions)

### ISSUE THREAD

**Issue by tex0l** [JiriHoffmann/react-native-cryptopp#6]
Would it be possible to expose the HMAC (and other MAC functions) you added in this commit (https://github.com/JiriHoffmann/react-native-cryptopp/commit/d2fac4e8b4667be858d1afe264e9be7dbbe0b836) to the exposed interface please?

**Comment by JiriHoffmann** [comment]
Working on it, will be out in next release
